stages:
  process:
    cmd: python src/process.py
    deps:
      - data/source/Housing.csv
      - params.yaml # 
    outs:
      - data/train/train.csv
      - data/test/test.csv

  train:
    cmd: python src/train.py
    deps:
      - data/train/train.csv
      - params.yaml
    outs:
      - models/model.pkl