process:
  data_source_path: data/source/Housing.csv
  data_processed_path: data/processed/processed.csv

split_data:
  test_size: 0.2
  seed: 42
  data_processed_path: data/processed/processed.csv
  data_train_path: data/train/train.csv
  data_test_path: data/test/test.csv

train:
  n_estimators: 130
  data_train_path: data/train/train.csv
  model_path: models/model.pkl
  

evaluate:
  data_train_path: data/train/train.csv
  data_test_path: data/test/test.csv
  model_path: models/model.pkl